<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behavior" nsURI="http://www.lcc.uma.es/Behavior/1.0" nsPrefix="behavior">
  <eClassifiers xsi:type="ecore:EClass" name="Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formalization" lowerBound="1"
        eType="#//FormalizationKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodelGD" upperBound="-1"
        eType="ecore:EClass GCS.ecore#//MetamodelGD"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="denseTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="helpers" upperBound="-1"
        eType="#//Helper" containment="true" eOpposite="#//Helper/behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true" eOpposite="#//Rule/behavior"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonInjectiveness" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="-1.0" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soft" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vbles" upperBound="-1"
        eType="#//Variable" containment="true" eOpposite="#//Variable/rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nacs" upperBound="-1" eType="#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//Behavior"
        eOpposite="#//Behavior/rules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" lowerBound="2"
        upperBound="-1" eType="#//Pattern" containment="true" eOpposite="#//Pattern/rule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="els" upperBound="-1" eType="#//PatternEl"
        containment="true" eOpposite="#//PatternEl/pattern"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" eOpposite="#//Rule/patterns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FormalizationKind">
    <eLiterals name="spo"/>
    <eLiterals name="dpo" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//PatternEl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sfs" upperBound="-1" eType="#//Slot"
        containment="true" eOpposite="#//Slot/object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classGD" eType="ecore:EClass GCS.ecore#//ClassGD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/src"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//PatternEl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Object"
        eOpposite="#//Object/outLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Object" eOpposite="#//Object/inLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionExec" eSuperTypes="#//PatternEl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//AtomicRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//ObjectRole" containment="true" eOpposite="#//ObjectRole/actionExec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//ActionStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualObject" lowerBound="1"
        eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionExec" lowerBound="1"
        eType="#//ActionExec" eOpposite="#//ActionExec/participants"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sf" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//Object" eOpposite="#//Object/sfs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oclValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//PatternEl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oclValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternEl" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="#//Pattern" eOpposite="#//Pattern/els"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clock" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicRule" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OngoingRule" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" eOpposite="#//Rule/vbles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Helper">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oclExpression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//Behavior"
        eOpposite="#//Behavior/helpers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionStatus">
    <eLiterals name="unfinished"/>
    <eLiterals name="realized" value="1"/>
    <eLiterals name="interrupted" value="2"/>
    <eLiterals name="aborted" value="3"/>
  </eClassifiers>
</ecore:EPackage>
